# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
clusterman:
  replicaCount: 1

  image:
    repository: sangho/clusterman
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 80

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

noti:
  image:
    repository: appropriate/curl
    tag: latest
    pullPolicy: IfNotPresent

onos:
  replicaCount: 3

  image:
    repository: opensona/onos-sona-nightly-docker
    tag: latest
    pullPolicy: IfNotPresent

  port:
    openflow: 6653
    ovsdb: 6640
    onos_web: 8181
    onos_ssh: 8101
    onos_cluster: 9876

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 80

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}