apiVersion: v1
kind: Service
metadata:
  name: clusterman-service
  labels:
    run: "{{ .Release.Name }}-clusterman-service"
  namespace: default
spec:
  ports:
  - port: 9191
    name: rest
  selector:
    run: "{{ .Release.Name }}-clusterman"
---
apiVersion: v1
kind: Service
metadata:
  name: sona-service
  labels:
    run: "{{ .Release.Name }}-sona-service"
spec:
  ports:
  - port: {{ .Values.onos.onos_ssh }}
    name: karaf
  - port: {{ .Values.onos.onos_web }}
    name: onos-rest
  - port: {{ .Values.onos.onos_cluster }}
    name: cluster
  - port: {{ .Values.onos.ovsdb }}
    name: ovs
  - port: {{ .Values.onos.openflow }}
    name: openflow
  selector:
    run: "{{ .Release.Name }}-sona"

